import Head from 'next/head';
import { useContext } from 'react';
import { ThemeContext } from 'src/components/ThemeContext';
import { Button } from 'src/stories/Atoms/Button';
import { Heading1 } from 'src/stories/Atoms/Heading1';
import { ScrollIndicator } from 'src/stories/Atoms/ScrollIndicator';
import { Section } from 'src/stories/Atoms/Section';
import { Menu } from 'src/stories/Organisms/Menu';

export default function Home() {
  const { theme } = useContext(ThemeContext);

  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={theme}>
        <Menu />
        <Section>
          <Heading1>
            HEY, I&apos;M <span className="text-primary">Lee Savage</span>
          </Heading1>
          <p>
            A JavaScript focused web developer that builds frontend and backend
            applications
          </p>
          <Button primary label={'Projects'} />
          <ScrollIndicator />
        </Section>
      </main>
    </>
  );
}
