import { ThemeContext } from '@components/ThemeContext';
import { Button } from '@stories/Atoms/Button';
import { Heading1 } from '@stories/Atoms/Heading1';
import { ScrollIndicator } from '@stories/Atoms/ScrollIndicator';
import { Section } from '@stories/Atoms/Section';
import { Menu } from '@stories/Organisms/Menu';
import Head from 'next/head';
import { useContext } from 'react';

export default function Home() {
  const { theme } = useContext(ThemeContext);

  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={theme}>
        <Menu />
        <Section className="h-screen" pattern>
          <Heading1>
            HEY, I&apos;M <span className="text-primary">Lee Savage</span>
          </Heading1>
          <p>
            A JavaScript focused web developer that builds frontend and backend
            applications
          </p>
          <Button primary label={'Projects'} />
          <ScrollIndicator />
        </Section>
        <Section>
          <Heading1>About Me</Heading1>
          <p>
            Here you will find more information about me, what I do, and my
            current skills mostly in terms of programming and technology
          </p>
          <Button primary label={'Projects'} />
        </Section>
      </main>
    </>
  );
}
